name: CI Angular app trough Github Actions
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  jobs: 
    build-master: 
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Use Node.js 16.x
          uses: actions/setup-node@v1
          with: 
            node-version: 16.x

        - name: list dir
          run: ls -la

        - name: Setup
          run: npm ci

        - name: show node_modules
          run: ls node_ modules
        
        - name: Test
          run: |
             ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
